IMAGE_NAME = "ubuntu/xenial64"
N = 2
ANSIBLE_VERBOSITY = "v"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end
      
    config.vm.define "youtube-k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.50.10", auto_config: true
        master.vm.network "forwarded_port", guest: 8080, host: 9090, host_ip: "127.0.0.1"

        master.vm.hostname = "youtube-k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
            ansible.verbose = ANSIBLE_VERBOSITY
            ansible.extra_vars = {
                node_ip: "192.168.50.10",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "youtube-k8s-worker-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}", auto_config: true
            node.vm.hostname = "youtube-k8s-worker-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/worker-playbook.yml"
                ansible.verbose = ANSIBLE_VERBOSITY
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{i + 10}",
                }
            end
        end
    end
end    